languageCode: "en"
title: "Flomi"
baseURL: "https://flomi.sipt.top"

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6

buildDrafts: true
buildFuture: true

enableRobotsTXT: true
metaDataFormat: "yaml"
disableKinds: ["404", "taxonomy", "term", "RSS"]

publishDir: "_site"

module:
  mounts:
    - source: dist
      target: static/docs/1.1/dist
    - source: site/assets
      target: assets
    - source: site/content
      target: content
    - source: site/data
      target: data
    - source: site/layouts
      target: layouts
    - source: site/static
      target: static
    - source: site/static/docs/1.1/assets/img/favicons/apple-touch-icon.png
      target: static/apple-touch-icon.png
    - source: site/static/docs/1.1/assets/img/favicons/favicon.ico
      target: static/favicon.ico

params:
  subtitle: "Quickly build a feature-rich workflow with GUI."
  description: "Powerful, extensible, and feature-packed productivity toolkit. Use multiple imported or custom Jobs to build a diverse Pipeline to automate tasks."
  authors: "Sipt Wu"
  keywords: "flomi app, flomi for mac, flomi for windows, workflow"

  current_version: "1.1.0"
  current_ruby_version: "1.0.0-alpha1"
  docs_version: "1.1"
  rfs_version: "v9.0.6"
  github_org: "https://github.com/sipt"
  repo: "https://github.com/sipt/flomi"
  discord: "https://discord.gg/6UGVTv6jMB"
  twitter: "sipt_wu"
  opencollective: "https://opencollective.com/bootstrap"
  blog: "https://blog.getbootstrap.com/"
  themes: "https://themes.getbootstrap.com/"
  icons: "https://icons.getbootstrap.com/"
  swag: "https://cottonbureau.com/people/bootstrap"

  download:
    macDist: "https://github.com/sipt/flomi-rls/releases/download/v1.1.0/flomi-darwin-universal-1.1.0.zip"
    winDist: "https://github.com/sipt/flomi-rls/releases/download/v1.1.0/flomi-1.1.0.Setup.exe"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
    css_hash: "sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
    css_rtl: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash: "sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51"
    js: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
    js_hash: "sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
    js_bundle: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash: "sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    popper: "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    popper_hash: "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"

  anchors:
    min: 2
    max: 5
